### PR TITLE
Change wording of port forwarding risks

### PR DESCRIPTION
**Pull request by ELKER54**
Changed wording of the risks of port forwarding and made it show up better:

image

### CODE REVIEW

**Comment by ELKER54** [comment]
Just hold off 2 seconds. Need to check something. Don't approve just yet

**Comment by ELKER54** [comment]
I messed up my bits. Will fix and create a new pull tomorrow

**Comment by O1LER** [comment]
You could also set it as draft

**Comment by ELKER54** [comment]
It was supposed to be 2 different bits. One which is needs to be changed quickly. One which was going to be changed at a later date

**Comment by ELKER54** [comment]
Np :)

**Pull request closed without merging**
