### PR TITLE
Translate /community/ to Italian

### PR DESCRIPTION
**Pull request by AlexITA1100**
Added translation for `/community/index.md` and `/community/rules.md`.
Fixed format to correctly display the page and have a table of contents.

### CODE REVIEW

**Review by O1LER — CHANGES_REQUESTED** [review]
Are you able to update the english version of the rules.md to the current one in the main branch? If not, can you remove it and add the changes to a separate PR?

**Review by O1LER — DISMISSED** [review]

**Comment by O1LER** [comment]
I guess i need to be clearer next time. I meant to remove the changes to `en/community/rules.md` in this PR by reverting the commits that touched that file, and then opening a new PR just for those Commits. But anyway, will fix it afterwards

**Review by ELKER54 — APPROVED** [review]

**Comment by Starystars67** [comment]
I think I like the formatting change that this PR has added on the en branch.
What does everyone else think?

**Comment by O1LER** [comment]
There was a conflict due to rule 1.09...

**Review by ELKER54 — APPROVED** [review]
Looks Good

**Pull request merged**
