### PR TITLE
Break out Server Scripting Reference by version

### PR DESCRIPTION
**Pull request by Starystars67**
As the title says this PR breaks out the server scripting versions to be clearer on the initial page keeping it to the latest version as standard but with the old docs for reference.

### CODE REVIEW

**Comment by O1LER** [comment]
Whats the reason to not move legacy stuff into its own page, hidden away? Server 2.x is outdated by years by now

**Comment by WiserTixx** [comment]
With this PR it is moved to its own page. And in my opinion it should still be visible if someone for example wants to port a script.

**Comment by Starystars67** [comment]
It is also still visible from the left hand links.

**Comment by O1LER** [comment]
Sorry, seems like ive scrolled over the file header part

**Review by O1LER — APPROVED** [review]

**Review by WiserTixx — APPROVED** [review]

**Pull request merged**
